typography_spectrum: 0.8956867528613657
color:
  brandStrength: 0.03741546254605055
  lightness: 0.8307713964022696
  saturation: 0.6991005453746766
  rhythmicContrast: 0.9416814167052507
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.01923374366015196
name: kidworld
title: Гэр бүлийн гишүүн бүрт мэдлэг түгээе
description: 'Үлгэр, шинжлэх ухаан, зураг, харилцаа'
